# Generated by Django 3.1.2 on 2020-12-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField(max_length=250)),
            ],
        ),
    ]
