# Generated by Django 3.1.2 on 2020-12-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_shouting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shouting',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='shouting',
            name='date',
            field=models.DateField(verbose_name='Date shouted'),
        ),
    ]
